/*
File: nav1.h
Module: Avionics Instruments, Dynamics for Seneca.

This file contains definitions for use with the KNS80 NAV1 box
*/

/***************************/
/*   Revision Record       */
/***************************/

/*
$Header: C:/SENECA/NAV/RCS/nav1.h 1.1 2000/02/22 02:23:56 juliae Exp $
$Log: nav1.h $
Revision 1.1  2000/02/22 02:23:56  juliae
Initial revision

*/

/*---------------------------------------------------------------*/

#define NAV1_VOR     0
#define NAV1_VOR_PAR 1
#define NAV1_RNV     2
#define NAV1_RNV_APR 3
